[package]
name = "rlobkit-app-events"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
log = "0.4"

[target.'cfg(target_os = "android")'.dependencies.jni]
version = "0.22"
optional = true

[package.metadata.android.cargo_rapk]
java_sources = "android"

[features]
default = []
jni-bridge = ["jni"]
android-log = ["dep:tracing", "dep:tracing-subscriber", "dep:tracing-log", "dep:paranoid-android"]

[target.'cfg(target_os = "android")'.dependencies]
tracing = { version = "0.1", default-features = false, features = ["std"], optional = true }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "env-filter",
    "fmt",
], optional = true }
tracing-log = { version = "0.2", default-features = false, features = ["log-tracer", "std"], optional = true }
paranoid-android = { version = "0.2", default-features = false, optional = true }
