[workspace]
members = [
    "rlobkit-core",
    "rlobkit-dialogs",
    "rlobkit-image",
    "rlobkit-app-events",
]
resolver = "3"

[workspace.package]
version = "0.5.6"
edition = "2024"
authors = ["mlm-games"]
license = "MIT"
description = "Partially cross-platform file-picking toolkit"
repository = "https://github.com/mlm-games/rlobkit"
homepage = "https://github.com/mlm-games/rlobkit"
rust-version = "1.85"

[workspace.dependencies]
rlobkit-core = { path = "rlobkit-core", version = "0.5.6" }
rlobkit-dialogs = { path = "rlobkit-dialogs", version = "0.5.6" }
rlobkit-image = { path = "rlobkit-image", version = "0.5.6" }
rlobkit-app-events = { path = "rlobkit-app-events", version = "0.5.6" }

# [patch.crates-io]
# rlobkit-core = { path = "../rlobkit/rlobkit-core" }

[profile.release]
lto = "thin"
